#!/bin/sh

set -eu

REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
GIT_NEST_REAL="$REPO_ROOT/bin/git-nest"
TEST_ROOT=${TEST_ROOT:-"${TMPDIR:-/tmp}/git-nest-test-workspaces"}
GIT_NEST_COMMAND_LOG=${GIT_NEST_COMMAND_LOG:-"$TEST_ROOT/.git-nest-commands.log"}

# Tests need MSYS2 path conversion ENABLED: git.exe is a native Windows binary
# and must translate /tmp workspace paths. The full-suite runner already
# neutralizes these variables; doing it here as well protects standalone runs
# (sh tests/integration-tests/test_XXXX.sh) from an inherited caller environment.
unset MSYS2_ARG_CONV_EXCL MSYS_NO_PATHCONV MSYS2_ENV_CONV_EXCL 2>/dev/null || true

# fd 9 is the curated narrative stream. The full-suite runner opens it to a
# per-test narrative file it streams to the console; a standalone test run has no
# fd 9, so fall back to stdout so narration is still visible.
if ! { true >&9; } 2>/dev/null; then
    exec 9>&1
fi

# Install a git-nest logging shim. Every invocation through $GIT_NEST or `git
# nest` echoes the command and its output to the narrative stream (fd 9) while
# still delivering real stdout/stderr, so assertions and captures are unaffected.
# The full-suite runner presets GIT_NEST_SHIM_DIR and owns it; a standalone run
# creates one via mktemp and cleans it up on exit.
_GIT_NEST_SHIM_SELF_CREATED=0
if [ -z "${GIT_NEST_SHIM_DIR:-}" ]; then
    GIT_NEST_SHIM_DIR=$(mktemp -d "${TMPDIR:-/tmp}/git-nest-shim.XXXXXX")
    _GIT_NEST_SHIM_SELF_CREATED=1
fi
trap '_GIT_NEST_SHIM_SELF_CREATED=${_GIT_NEST_SHIM_SELF_CREATED:-0}; [ "$_GIT_NEST_SHIM_SELF_CREATED" -eq 1 ] && rm -rf "$GIT_NEST_SHIM_DIR" 2>/dev/null || true' EXIT
mkdir -p "$GIT_NEST_SHIM_DIR"
cat >"$GIT_NEST_SHIM_DIR/git-nest" <<SHIM
#!/bin/sh
# Generated by tests/helper.sh: log the git-nest command and its output to the
# narrative stream (fd 9) and the command trace file, then deliver the real
# streams unchanged.
gn_real="$GIT_NEST_REAL"
gn_log="$GIT_NEST_COMMAND_LOG"
mkdir -p "\$(dirname "\$gn_log")" 2>/dev/null || true
{ printf 'git-nest'; for gn_a in "\$@"; do printf ' %s' "\$gn_a"; done; printf '\n'; } >>"\$gn_log" 2>/dev/null || true
{ printf 'RUN: git-nest'; for gn_a in "\$@"; do printf ' %s' "\$gn_a"; done; printf '\n'; } >&9 2>/dev/null || true
gn_o=\$(mktemp); gn_e=\$(mktemp)
"\$gn_real" "\$@" >"\$gn_o" 2>"\$gn_e"; gn_rc=\$?
{ sed 's/^/    /' "\$gn_o"; [ -s "\$gn_e" ] && sed 's/^/    /' "\$gn_e"; printf '    [exit %s]\n' "\$gn_rc"; } >&9 2>/dev/null || true
cat "\$gn_o"
cat "\$gn_e" >&2
rm -f "\$gn_o" "\$gn_e"
exit \$gn_rc
SHIM
chmod +x "$GIT_NEST_SHIM_DIR/git-nest"
GIT_NEST="$GIT_NEST_SHIM_DIR/git-nest"
PATH="$GIT_NEST_SHIM_DIR:$PATH"
export PATH

# Keep test output deterministic regardless of a developer's global Git config.
# The overrides also apply to repositories cloned during tests.
GIT_CONFIG_COUNT=4
GIT_CONFIG_KEY_0=core.autocrlf
GIT_CONFIG_VALUE_0=false
GIT_CONFIG_KEY_1=core.eol
GIT_CONFIG_VALUE_1=lf
GIT_CONFIG_KEY_2=core.safecrlf
GIT_CONFIG_VALUE_2=false
GIT_CONFIG_KEY_3=advice.detachedHead
GIT_CONFIG_VALUE_3=false
export GIT_CONFIG_COUNT
export GIT_CONFIG_KEY_0 GIT_CONFIG_VALUE_0
export GIT_CONFIG_KEY_1 GIT_CONFIG_VALUE_1
export GIT_CONFIG_KEY_2 GIT_CONFIG_VALUE_2
export GIT_CONFIG_KEY_3 GIT_CONFIG_VALUE_3
GIT_AUTHOR_NAME="git-nest test"
GIT_AUTHOR_EMAIL="git-nest@example.invalid"
GIT_COMMITTER_NAME="git-nest test"
GIT_COMMITTER_EMAIL="git-nest@example.invalid"
export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL

# All narration goes to the narrative stream (fd 9) so the runner can show a
# curated per-test story while the raw command output collects separately.

# Print a stable test identity for both full-suite and individual runs.
test_begin() {
    name=$1
    [ "${TEST_RUNNER_HEADING:-0}" = 1 ] && return 0
    number=${TEST_NUMBER:-00}
    printf 'TEST %s %s\n' "$number" "$name" >&9
}

TEST_STEP_NUMBER=0

# Echo a command as a RUN: line on the narrative stream so the console shows
# exactly what the test executes next. git-nest invocations are skipped because
# the shim already logs them (avoids duplicate RUN lines).
print_command() {
    # git-nest invocations are already logged by the shim, so skip them here to
    # avoid a duplicate RUN line.
    [ "${1:-}" = "$GIT_NEST" ] && return 0
    {
        printf 'RUN:'
        for arg in "$@"; do
            case "$arg" in
                *[!A-Za-z0-9_./:=,@%+-]*|'')
                    quoted=$(printf "%s" "$arg" | sed "s/'/'\\\\''/g")
                    printf " '%s'" "$quoted"
                    ;;
                *) printf ' %s' "$arg" ;;
            esac
        done
        printf '\n'
    } >&9
}

# Start a new numbered test step with its What/Why narration, partitioning the
# test into visible phases the runner streams to the console.
test_step() {
    TEST_STEP_NUMBER=$((TEST_STEP_NUMBER + 1))
    printf '\nStep %s: %s\n' "$TEST_STEP_NUMBER" "$1" >&9
    printf 'Why: %s\n' "$2" >&9
}

# Close the test with a one-line RESULT: summary on the narrative stream.
describe_result() {
    printf 'RESULT: %s\n' "$1" >&9
}

# Run a command that must succeed, narrating it, and fail the test if it
# exits nonzero (protects assertions under set -e with a clear message).
run_ok() {
    description=$1
    shift
    [ "${1:-}" = "--" ] || {
        printf 'run_ok requires -- before the command\n' >&2
        exit 1
    }
    shift
    print_command "$@"
    "$@"
    printf 'OK: %s\n' "$description" >&9
}

# Run a command that must fail with the expected exit code (or any nonzero
# exit when "any"), narrating it, and fail the test on a wrong result.
run_fail() {
    description=$1
    expected=$2
    shift 2
    [ "${1:-}" = "--" ] || {
        printf 'run_fail requires -- before the command\n' >&2
        exit 1
    }
    shift
    print_command "$@"
    set +e
    "$@"
    actual=$?
    set -e
    if [ "$expected" = any ]; then
        [ "$actual" -ne 0 ] || {
            printf 'UNEXPECTED RESULT: expected command to fail, but it exited 0\n' >&2
            exit 1
        }
    elif [ "$actual" -ne "$expected" ]; then
        printf 'UNEXPECTED RESULT: expected exit code %s, got %s for:' "$expected" "$actual" >&2
        printf ' %s' "$@" >&2
        printf '\n' >&2
        exit 1
    fi
    printf 'EXPECTED FAIL: %s\n' "$description" >&9
}

# Run a command that must succeed while capturing stdout/stderr to files so
# the test can assert on them; narrates the command and the capture paths.
run_capture() {
    description=$1
    stdout_file=$2
    stderr_file=$3
    shift 3
    [ "${1:-}" = "--" ] || {
        printf 'run_capture requires -- before the command\n' >&2
        exit 1
    }
    shift
    print_command "$@"
    "$@" >"$stdout_file" 2>"$stderr_file"
    printf 'OK: %s Output captured in %s and %s.\n' "$description" "$stdout_file" "$stderr_file" >&9
}

# Allocate a numbered persistent workspace for one test.
test_workspace() {
    name=$1
    number=${TEST_NUMBER:-00}
    work="$TEST_ROOT/test_${number}_$name"
    case "$work" in
        "$TEST_ROOT"/test_*) ;;
        *) echo "Refusing to use workspace outside test root: $work" >&2; exit 1 ;;
    esac
    mkdir -p "$work"
    printf '%s\n' "$work"
}

# Configure commit identity for local repositories created by tests.
git_config() {
    git config user.name "git-nest test"
    git config user.email "git-nest@example.invalid"
    git config core.autocrlf false
    git config core.eol lf
    git config core.safecrlf false
	git config advice.detachedHead false
	# Ensure git init and git init --bare default to "main" regardless of the
	# user's global init.defaultBranch setting (some systems, notably macOS
	# where git is installed via homebrew, may have init.defaultBranch=master).
	git config init.defaultBranch main
}

# Create a normal repository on main, tolerating older Git without init -b.
make_repo() {
    dir=$1
    mkdir -p "$dir"
    git -C "$dir" init -b main >/dev/null 2>&1 || {
        git -C "$dir" init >/dev/null
        git -C "$dir" checkout -b main >/dev/null
    }
    (cd "$dir" && git_config)
}

# Create a bare remote seeded with one initial commit on main.
make_bare_remote() {
    remote=$1
    work=$2
    make_repo "$work"
    printf 'initial\n' >"$work/file.txt"
    git -C "$work" add file.txt
    git -C "$work" commit -m "initial" >/dev/null
    git -C "$work" init --bare --initial-branch=main "$remote" >/dev/null 2>&1 || git -C "$work" init --bare "$remote" >/dev/null
    git -C "$work" remote add origin "$remote"
    git -C "$work" push -u origin main >/dev/null
    git -C "$remote" symbolic-ref HEAD refs/heads/main
}

# Assert that a file contains literal text; tests use this for manifest checks.
assert_file_contains() {
    file=$1
    text=$2
    grep -F -- "$text" "$file" >/dev/null || {
        printf 'UNEXPECTED RESULT: expected %s to contain: %s\n' "$file" "$text" >&2
        exit 1
    }
}

# Assert that a file does not contain literal text.
assert_file_not_contains() {
    file=$1
    text=$2
    if grep -F -- "$text" "$file" >/dev/null; then
        printf 'UNEXPECTED RESULT: expected %s not to contain: %s\n' "$file" "$text" >&2
        exit 1
    fi
}

# Run a command under set +e and fail the test unless its exit code matches
# the expected value, with a clear message showing the actual result.
assert_exit_code() {
    expected=$1
    shift
    set +e
    "$@"
    actual=$?
    set -e
    if [ "$actual" -ne "$expected" ]; then
        printf 'UNEXPECTED RESULT: expected exit code %s, got %s for:' "$expected" "$actual" >&2
        printf ' %s' "$@" >&2
        printf '\n' >&2
        exit 1
    fi
}
